apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
      - name: docker-test
        image: lipemiranda159/docker-test:2.0
        ports:
        - containerPort: 5000
